### ISSUE TITLE
Which GPL license do you mean?

### ISSUE THREAD

**Issue by kozross** [dommmel/coffee-snake#3]
There's quite a bit of difference  between the versions, so you might wanna clarify that.

**Comment by dommmel** [comment]
Yeah, I guess the free for non-commercial use is also not compatible with any GPL.
Do you want to use it and would like it to be licensed a certain way?

**Comment by kozross** [comment]
dommel: I'm compiling a collection of resources for free software and free culture game developers [here](https://notabug.org/koz.ross/awesome-gamedev), and I want to include your work. This requires clear licensing terms.

I would prefer GPL3 or later, but GPL2 is OK as well.

**Comment by dommmel** [comment]
OK, changed it to GPL v3. 
Cheers!
