### ISSUE TITLE
Clarify GPL version.

### ISSUE THREAD

**Issue by Jookia** [dommmel/coffee-snake#4]
Currently the GPL is included as a LICENSE.txt, but the source code doesn't contain any headers acknowledging this or a mention explicitly if it's the GPLv3 only or GPLv3+.

**Comment by dommmel** [comment]
A pull request would be much appreciated. Make it GPLv3+ if you think that's the better option. But please explain the whys in the pull request. That woul help me (and everybody reading this) understand why it's important to do this stuff correctly.

**Comment by Jookia** [comment]
Shall do!

**Comment by dommmel** [comment]
Thanks for the informative pull request.
